### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by unlight** [hippich/baucis-access#2]
I'm trying to do as written in readme.
```js
var baucis = require('baucis');
var access = require('baucis-access');
var userModel = require("./userModel.js");
var controller = baucis.rest(userModel);
// controller is express router object
controller.access({}); // TypeError: Object function router ...  has no method 'access'
```

**Comment by unlight** [comment]
baucis 1.0.5

**Comment by hippich** [comment]
this plugin coded against baucis v1.0.0-candidate.8, which probably changed since then and might explain issue. If you have time to debug it - feel free to submit PR, it is probably something minor.

**Comment by unlight** [comment]
@wprl Could you take a look?

**Comment by unlight** [comment]
I think I realized the issue.
`baucis` from your module and from my are referenced to different objects.
So, you need move it from `dependencies` to `devDependencies`, or remove it at all.

**Comment by hippich** [comment]
I remember somewhat similar issue. Did you download it directly into node_modules folder? or did npm install baucis-access --save ?

**Comment by hippich** [comment]
I just looked at my own project where I am using baucis-access and I have no `baucis` in `project/node_modules/baucis-access/node_modules/` I think the only way to get it there is to run `npm install` inside `project/node_modules/baucis-access/` folder.

**Comment by hippich** [comment]
In fact, someone (@Tuxion) already solved this issue in their own fork :) - https://github.com/Tuxion/baucis-access/commit/d5d0e2e5d624cd144c909083e7b6089ca9fb3b86 - I am going to do similar change.

**Comment by unlight** [comment]
Sweet.

**Comment by hippich** [comment]
Please try baucis-access@0.0.5 to see if issue is solved for you

**Comment by unlight** [comment]
It works. Dont forget publish to npm new version,

**Comment by hippich** [comment]
Cool, thanks for helping fix that!
